package com.ireslab.sendx.electra.utils;

/**
 * @author Nitin
 *
 */
public enum ResponseCode {
	Success(200),

	FAIL(4000),

	TOKEN_MANAGEMENT_USER_NOT_FOUND(1000),

	TOKEN_MANAGEMENT_CLIENT_ASSET_TOKEN_NOT_FOUND(1001),

	TOKEN_MANAGEMENT_USER_LOCK(1002),

	TOKEN_MANAGEMENT_USER_TOKEN_LOCK(1003),

	TRANSACTION_MANAGER_TRANSFER_LUMENS_TOKEN_FAIL(1100),

	TOKEN_MANAGEMENT_PAYMENT_TRANSACTION_FAILURE(1102),

	STELLAR_ACCOUNT_INSUFFICIENT_BALANCE(1200),

	STELLAR_DESTINATION_ACCOUNT_DOESNOT_EXISTS(1300),

	STELLAR_TRUSTLINE_CREATION_FAILED(1301),

	STELLAR_ACCOUNT_BALANCE_OPERATION_FAILED(1302),

	STELLAR_ACCOUNT_CREATION_FAILED(1303),
	
	CLIENT_CREDENTIAL_ACTIVATION_SUCCESS(1401),
	
	CLIENT_CREDENTIAL_ACTIVATION_FAIL(1402),
	
	COUNTRY_DIAL_CODE_NOT_FOUND(1501);

	private Integer code;

	private ResponseCode(Integer code) {
		this.code = code;
	}

	public Integer getCode() {
		return code;
	}
}
